### ISSUE TITLE
Feature request for AWS deploy config

### ISSUE THREAD

**Issue by Cally99** [chrisk314/django-celery-docker-example#2]
Hi, Thanks for the boilerplate. It's very detailed and clean designed.
I do however have a question about Nginx. I've had my own app in Dev mode and it uses nginx and docker very similar set up as this repo. I'm having difficulties setting up Nginx settings to accept the url that's created in my EC2 instance.

Would you have any interest in sharing or updating production deployment settings for Nginx?
Thanks for the great repo by the way!

**Comment by chrisk314** [comment]
Hi @Cally99 sorry for the reply over a year later! Never noticed the issues opened on this repo. Obviously you solved whatever you were doing with nginx by now.

I don't have any plans to do any more work on this repo (as you can probably tell!).

Fyi this [h5bp repo](https://github.com/h5bp/server-configs-nginx) is a really excellent source of production grade nginx config files which gives very detailed explanation of the options. I used their config files in another repo demonstrating a golang and riotjs app with auto renewing SSL certs which you can see [here](https://github.com/chrisk314/riotjs-nginx-example-app) if you're interested.
