### ISSUE TITLE
wait-for not found

### ISSUE THREAD

**Issue by rob101** [chrisk314/django-celery-docker-example#3]
When deploying, this Dockerfile uses the latest version of Alpine (currently `python:3.8.1-alpine3.11` at the time of writing).

However, this results in `/bin/sh: wait-for: not found` when `docker-compose` up is run.

I've tried to debug it but without luck.

The file is definitely there. When I use `docker-compose run app sh --rm` in powershell I can see the file in the directory structure; however I get the same error when I try to execute it from the shell manually.

```
/usr/src/app $ wait-for
sh: wait-for: not found
```

Could something have changed in a recent release to break this?

`LDD wait-for` returns it is not a dynamic program.

**Comment by artyomLisovskij** [comment]
wait-for https://github.com/chrisk314/django-celery-docker-example/blob/master/wait-for it's just a script. did you try to run it using: `./wait-for` or `sh wait-for`?

**Comment by chrisk314** [comment]
I haven't looked at this repo in a long time! Didn't notice there were open issues here. I'm not actively maintaining this.

I couldn't reproduce the issue mentioned here. `wait-for` is a script which gets copied into the container during build time as documented in the README. I just cloned this and tried the command you mentioned and it all works fine. You mentioned `powershell` so guess that means WIndows. Maybe things work differently on Windows. I use Ubuntu. No intention to adapt for Windows specific quirks.

```
$ docker-compose run app sh --rm
WARNING: Some services (celery_worker) use the 'deploy' key, which will be ignored. Compose does not support 'deploy' configuration - use `docker stack deploy` to deploy to a swarm.
Starting postgres ... done
Starting rabbitmq ... done
/usr/src/app # which wait-for
/bin/wait-for
```
