### ISSUE TITLE
client unexpectedly closed TCP connection

### ISSUE THREAD

**Issue by riccardogl** [chrisk314/django-celery-docker-example#4]
Hi. I encountered error from rabbitmq: client unexpectedly closed TCP connection. Should I configure anything behind corporate proxy?

**Comment by chrisk314** [comment]
Hi Sorry for delayed response. Never saw this opened issue. I'm not maintaining this repo anymore. I'm not an expert in network configuration so I don't know the answer to this question. Hope you managed to figure things out.
